[appinfo]
VITE_APPWEBSITE = "https://www.lalulla.com"


[globalvariables]
VITE_API_URL = "https://api.example.com"
VITE_APP_TITLE = "Lalulla System"
VITE_ENTITYID = "CGONE"
VITE_APPID = "LALULLA"
VITE_APPVERSION = "1.0.0"
